### ISSUE TITLE
Can't generate WooCommerce products

### ISSUE THREAD

**Issue by jmcbee** [trendwerk/faker#11]
```
# image.yml
Trendwerk\Faker\Entity\Image:
  image{1..5}:
    data: '<image()>'
```

```
Trendwerk\Faker\Entity\Post:
  post{1..30}:
    post_content: <paragraphs(4, true)>
    post_title: '<words()>'
    post_type: 'product'
    terms:
      category: <terms('category', 3)>
    meta:
      _thumbnail_id: '@image*->id'
      _price: '<randomDigit()>'
      _visibility: 'visible'
```

The output is:

```
Warning: trim() expects parameter 1 to be string, array given in /var/www/public/wp-includes/class-wp-hook.php on line 298
Success: Generated 35 new posts.
```

I'm not sure what I could have done wrong. Also, is it possible to re-use a field? Like use the set value of `_price` on another meta field `_regular_price`. Thanks!

**Comment by haroldangenent** [comment]
@fbm-static Sorry for my slow response, didn't get a chance to look at this sooner. I have tried generating products for WooCommerce with success. My findings when using your suggested `yml` files:

>Warning: trim() expects parameter 1 to be string, array given in /var/www/public/wp-includes/class-wp-hook.php on line 298

Could you try using `sentence()` for `post_title` (instead of `words()`)? Words actually returns an array, while `post_title` should be a string. So:

```
post_title: '<sentence()>'
```

_By the way, I noticed you are using the term `category`, but the WooCommerce product category is called `product_cat`. I'm not sure about your setup (you might have a taxonomy called `category`), but if you want to populate using your existing WooCommerce product categories, you should use `product_cat`._

>  Also, is it possible to re-use a field? Like use the set value of _price on another meta field _regular_price.

It seems you can self-reference objects by using `@self` (for example, you can use `<(@self->post_author)>`), but I cannot seem to get this to work for `meta`, because it's not set yet when it encounters `_regular_price`. This _would_ be possible if you would create a custom provider based on `Post`.

If there were a property that has a set price, you could re-use this for `_price` and `_regular_price`. For example, when using `post_author` as an example (which you shouldn't do) in `product.yml`:

```
include:
  - image.yml

Trendwerk\Faker\Entity\Post:
  post{1..1}:
    post_content: <paragraphs(4, true)>
    post_title: '<sentence()>'
    post_type: 'product'
    post_author: '<randomDigit()>'
    terms:
      category: <terms('product_cat', 3)>
    meta:
      _thumbnail_id: '@image*->id'
      _price: '<(@self->post_author)>'
      _regular_price: '<(@self->post_author)>'
      _visibility: 'visible'
```

Hope this helps. I'll close this issue for now, since there's probably not something that should be added or changed in the library. Let me know if you find an improvement that could be made.
